### ISSUE TITLE
Roadmap!

### ISSUE THREAD

**Issue by flapjax** [flapjax/FlapJack-Cogs#21]
# FlapJack Cogs Roadmap
If you're curious about what I'm working on, I will use this issue as a roadmap.

### Blizzard
- [x] Remove Pandoc dependency, handle HTML parsing inside cog
- [x] Better formating for notes, using code blocks and syntax highlighting
- [x] Add paginated option for displaying notes, with a reaction menu for navigation
- [ ] Add embedded summary option for displaying notes 
- [ ] Detection and announcement of new patch notes
- [ ] Enhance Overwatch statistics (and fix problems with seasonal stats)

### SFX
- [ ] Improve async queuing
- [ ] ***TRY*** to enhance compatibility with [Audio](http://i.imgur.com/omYnlOZ.gifv) further, e.g. in cases where the SFX queue is playing and someone tries to steal it back with Audio commands.
- [ ] Expose SFX queue to other cogs

### gTTS
- [ ] Find a TTS engine that can be installed locally with the cog
- [ ] Support for additional languages

### msgvote
- [ ] Remove bot reactions after the voting period has ended
- [ ] Rework vote counting to use listeners instead of tasks & get_message -- *should* reduce API calls for busy servers

### ReactPoll
- [ ] Remove bot reactions after the voting period has ended

### Smite
- [ ] Patch notes
- [ ] More clan features

## Future Cogs
😉
